const express = require('express');
const router = express.Router();
const { login, registerStudent, refreshToken, getMe, logout } = require('../controllers/authController');
const { protect } = require('../middleware/auth');
router.post('/login', login);
router.post('/register', registerStudent);
router.post('/refresh', refreshToken);
router.get('/me', protect, getMe);
router.post('/logout', protect, logout);
module.exports = router;
